export const localizeTable = {
  EN: {
    combatClass: {
      Main: "Striker",
      Support: "Special",
    },

    attackType: {
      Explosion: "Explosive",
      Pierce: "Piercing",
      Mystic: "Mystic",
      Normal: "Normal",
      Sonic: "Sonic",
      Mixed: "Mixed",
    },

    defenseType: {
      LightArmor: "Light",
      HeavyArmor: "Heavy",
      Unarmed: "Special",
      ElasticArmor: "Elastic",
      Normal: "Normal",
      Mixed: "Mixed",
    },

    combatRole: {
      DamageDealer: "Dealer",
      Tanker: "Tank",
      Healer: "Healer",
      Supporter: "Support",
      Vehicle: "T.S.",
    },

    combatPosition: {
      Back: "Back",
      Front: "Front",
      Middle: "Middle",
    },

    skillType: {
      EX: "EX",
      Basic: "Basic",
      Enhanced: "Enhanced",
      Sub: "Sub",
    },

    school: {
      Abydos: "Abydos High School",
      Arius: "Arius Satellite School",
      Gehenna: "Gehenna Academy",
      Hyakkiyako: "Allied Hyakkiyako Academy",
      Millennium: "Millennium Science School",
      RedWinter: "Red Winter Federal Academy",
      Shanhaijing: "Shanhaijing Academy",
      SRT: "SRT Academy",
      Trinity: "Trinity General School",
      Valkyrie: "Valkyrie Police School",
      ETC: "ETC",
      Tokiwadai: "Tokiwadai Middle School",
      Sakugawa: "Sakugawa Middle School",
    },

    terrain: {
      Street: "Urban",
      Outdoor: "Field",
      Indoor: "Indoor",
    },

    club: {
      Kohshinjo68: "Problem Solver 68",
      Justice: "Justice Task Force",
      CleanNClearing: "Cleaning & Clearing",
      BookClub: "Library Committee",
      Countermeasure: "Foreclosure Task Force",
      Engineer: "Engineering Department",
      FoodService: "School Lunch Club",
      Fuuki: "Prefect Team",
      GourmetClub: "Gourmet Research Society",
      HoukagoDessert: "After-School Sweets Club",
      KnightsHospitaller: "Remedial Knights",
      MatsuriOffice: "Festival Operations Department",
      Meihuayuan: "Plum Blossom Garden",
      Onmyobu: "Yin-Yang Club",
      RemedialClass: "Make-Up Work Club",
      SPTF: "Super Phenomenon Task Force",
      Shugyobu: "Inner Discipline Club",
      Endanbou: "Eastern Alchemy Society",
      TheSeminar: "Seminar",
      TrainingClub: "Athletics Training Club",
      TrinityVigilance: "Trinity's Vigilante Crew",
      Veritas: "Veritas",
      NinpoKenkyubu: "Ninjutsu Research Club",
      GameDev: "Game Development Department",
      RedwinterSecretary: "Red Winter Office",
      anzenkyoku: "Public Safety Bureau",
      SisterHood: "The Sisterhood",
      Class227: "Spec Ops No. 227",
      Emergentology: "Medical Emergency Club",
      RabbitPlatoon: "RABBIT Squad",
      PandemoniumSociety: "Pandemonium Society",
      AriusSqud: "Arius Squad",
      HotSpringsDepartment: "Hot Springs Department",
      TeaParty: "Tea Party",
      PublicPeaceBureau: "Public Peace Bureau",
      BlackTortoisePromenade: "Black Tortoise Promenade",
      Genryumon: "Genryumon",
      LaborParty: "Labor Party",
      KnowledgeLiberationFront: "Knowledge Liberation Front",
      Hyakkayouran: "Hyakkaryouran Resolution Council",
      ShinySparkleSociety: "Sparkle Club",
      AbydosStudentCouncil: "Abydos Student Council",
      EmptyClub: "None",
    },

    weaponType: {
      SR: "Sniper Rifle",
      SG: "Shotgun",
      AR: "Assault Rifle",
      MG: "Machine Gun",
      SMG: "Submachine Gun",
      RG: "Railgun",
      HG: "Handgun",
      GL: "Grenade Launcher",
      RL: "Rocket Launcher",
      FT: "Flamethrower",
      MT: "Mortar",
    },

    stat: {
      Level: "Level",
      MaxHP: "Max HP",
      AttackPower: "ATK",
      DefensePower: "DEF",
      HealPower: "Healing",
      AccuracyPoint: "Accuracy",
      DodgePoint: "Evasion",
      CriticalPoint: "Crit",
      CriticalDamageRate: "Crit DMG",
      HealEffectivenessRate: "Recovery Boost",
      OppressionPower: "CC Power",
      OppressionResist: "CC RES",
      CriticalChanceResistPoint: "Crit RES",
      CriticalDamageResistRate: "Crit DMG RES",
      StabilityPoint: "Stability",
      StabilityRate: "Stability Rate",
      Range: "Normal Attack Range",
      AmmoCount: "Mag Count",
      AmmoCost: "Normal Attack Cost",
      MoveSpeed: "MOV SPD",
      DamageRatio: "DMG Dealt (Enemy)",
      DamageRatio2: "DMG Dealt",
      DamagedRatio: "DMG Resist (Enemy)",
      DamagedRatio2: "DMG Resist",
      ExDamagedRatio: "EX Skill DMG Resist",
      EnhanceExDamageRate: "EX Skill DMG Dealt",
      AttackSpeed: "ATK SPD",
      BlockRate: "Block Rate Bonus",
      DefensePenetration: "Defense Piercing",
      RegenCost: "Cost Recovery",
      EnhanceExplosionRate: "Explosive Effectiveness",
      EnhancePierceRate: "Piercing Effectiveness",
      EnhanceMysticRate: "Mystic Effectiveness",
      EnhanceSonicRate: "Sonic Effectiveness",
      EnhanceLightArmorRate: "Light Armor Enhancement",
      EnhanceHeavyArmorRate: "Heavy Armor Enhancement",
      EnhanceUnarmedRate: "Special Armor Enhancement",
      EnhanceElasticArmorRate: "Elastic Armor Enhancement",
      ExtendBuffDuration: "Buff Retention",
      ExtendDebuffDuration: "Debuff Retention",
      ExtendCrowdControlDuration: "CC Retention",
      SkillCost: "EX Skill Cost",
      NormalHits: "Normal Attack Hits",
      EXHits: "EX Skill Hits",
      PublicHits: "Basic Skill Hits",
      GroggyGauge: "Groggy Gauge",
      GroggyTime: "Groggy Duration",
      LostHP: "Lost HP",
      CurrentHP: "HP",
      BurnDamagedIncrease: "Burn DMG Taken",
      ChillDamagedIncrease: "Chill DMG Taken",
      ElectricShockDamagedIncrease: "Shock DMG Taken",
      PoisonDamagedIncrease: "Poison DMG Taken",
      IgnoreDelayCount: "Ignore Delay",
    },

    buffName: {
      Buff_AidAttitude: "Aiding Mindset",
      Buff_AmmoCount: "Mag Count",
      Buff_ATK: "ATK",
      Buff_AttackSpeed: "ATK SPD",
      Buff_BlockRate: "Block Rate",
      Buff_ConcentratedTarget: "Focused Assault",
      Buff_CostChange: "EX Skill Cost",
      Buff_CostRegen: "Cost Recovery",
      Buff_CriticalChance: "Crit",
      Buff_CriticalChanceResistPoint: "Crit RES",
      Buff_CriticalDamage: "Crit DMG",
      Buff_CriticalDamageRateResist: "Crit DMG RES",
      Buff_DamagedLimit: "Max DMG Limit",
      Buff_DamagedRatio: "Incoming Damage",
      Buff_DamageRatio: "Damage Dealt",
      Buff_DEF: "DEF",
      Buff_Dodge: "Evasion",
      Buff_DotHeal: "HP Regen",
      Buff_EnhanceExplosionRate: "Explosive Effectiveness",
      Buff_EnhancePierceRate: "Piercing Effectiveness",
      Buff_EnhanceMysticRate: "Mystic Effectiveness",
      Buff_EnhanceSonicRate: "Sonic Effectiveness",
      Buff_EnhanceLightArmorRate: "Lgt. Armor Enhancement",
      Buff_EnhanceHeavyArmorRate: "Hvy. Armor Enhancement",
      Buff_EnhanceUnarmedRate: "Spc. Armor Enhancement",
      Buff_ExtendBuffDuration: "Buff Retention",
      Buff_ExtendDebuffDuration: "Debuff Retention",
      Buff_ExtendCrowdControlDuration: "CC Retention",
      Buff_HealByHit_Damaged: "Heal When Hit",
      Buff_HealEffectiveness: "Recovery Boost",
      Buff_HealPower: "Healing",
      Buff_HIT: "Accuracy",
      Buff_MAXHP: "Max HP",
      Buff_MoveSpeed: "MOV SPD",
      Buff_OppressionPower: "CC Power",
      Buff_OppressionResist: "CC RES",
      Buff_Penetration: "Defense Piercing",
      Buff_Range: "Normal Atk. Range",
      Buff_Shield: "Barrier",
      Buff_Stability: "Stability",
      Buff_EnhanceExDamageRate: "EX Skill DMG Dealt",
      Debuff_AmmoCount: "Mag Count",
      Debuff_ATK: "ATK",
      Debuff_AttackSpeed: "ATK SPD",
      Debuff_BlockRate: "Block Rate",
      Debuff_Burn: "Burn",
      Debuff_Cheerleading: "Passionate Cheering",
      Debuff_Chill: "Chill",
      Debuff_ConcentratedTarget: "Focused Assault",
      Debuff_CostChange: "EX Skill Cost",
      Debuff_CriticalChance: "Crit",
      Debuff_CriticalChanceResistPoint: "Crit RES",
      Debuff_CriticalDamage: "Crit DMG",
      Debuff_CriticalDamageRateResist: "Crit DMG RES",
      Debuff_DamageByHit_Damaged: "Weakness Detection",
      Debuff_DamagedRatio: "Incoming Damage",
      Debuff_DamageRatio: "Damage Dealt",
      Debuff_DEF: "DEF",
      Debuff_Dodge: "Evasion",
      Debuff_EnhanceExplosionRate: "Explosive Effectiveness",
      Debuff_EnhancePierceRate: "Piercing Effectiveness",
      Debuff_EnhanceMysticRate: "Mystic Effectiveness",
      Debuff_EnhanceSonicRate: "Sonic Effectiveness",
      Debuff_EnhanceLightArmorRate: "Lgt. Armor Effectiveness",
      Debuff_EnhanceHeavyArmorRate: "Hvy. Armor Effectiveness",
      Debuff_EnhanceUnarmedRate: "Spc. Armor Effectiveness",
      Debuff_HealedLimit: "Recovery Limit",
      Debuff_HealEffectiveness: "Recovery Boost",
      Debuff_HealPower: "Healing",
      Debuff_Hieronymus: "Curse",
      Debuff_HIT: "Accuracy",
      Debuff_MAXHP: "Max HP",
      Debuff_MoveSpeed: "MOV SPD",
      Debuff_OppressionPower: "CC Power",
      Debuff_OppressionResist: "CC RES",
      Debuff_Penetration: "Defense Piercing",
      Debuff_Poison: "Poison",
      Debuff_Range: "Normal Atk. Range",
      Debuff_ElectricShock: "Shock",
      Debuff_Stability: "Stability",
      Debuff_EnhanceExDamageRate: "EX Skill DMG Dealt",
      Debuff_CostRegen: "Cost Recovery",
      Debuff_BurnDamagedIncrease: "Burn DMG Taken",
      Debuff_ChillDamagedIncrease: "Chill DMG Taken",
      Debuff_ElectricShockDamagedIncrease: "Shock DMG Taken",
      Debuff_PoisonDamagedIncrease: "Poison DMG Taken",
      CC_Fear: "Fear",
      CC_Stunned: "Stun",
      CC_Provoke: "Taunt",
      CC_Paralysis: "Paralysis",
      CC_Emp: "EMP",
      CC_Confusion: "Confusion",
      CC_Frozen: "Freeze",
      Special_EnergyBatteryEmpty: "Energy Charge",
      Special_EnergyBatteryHalf: "Half Charge",
      Special_EnergyBatteryFull: "Full Charge",
      Special_FormChange: "Normal Attack",
      Special_Immortal: "Invincible",
      Special_ImmuneDamage: "Invulnerable",
      Special_Fury: "Enraged",
      Special_Misdeed: "Evil Deeds",
      Special_LittleDevil: "Imps",
      Special_Accumulation: "Accumulation",
      Special_CostRegenBan: "Recovery Stop",
      Special_ImmuneCC: "CC Immune",
      Special_SuddenDeath: "Wakamo Imprint",
      Special_Stamp: "Stamps of Praise",
      Special_Holiday: "Holy Night's Blessing",
      Special_SilverBullet: "Normal Attack",
      Special_CH0187Mod: "Abi-Eshuh Mode",
      Special_Omamori: "Amulet",
      Special_Dado: "Serenity",
      Special_DebuffCountGreen: "Safe",
      Special_DebuffCountYellow: "Warning",
      Special_DebuffCountRed: "Danger",
      Special_OldBook: "Clues",
      Special_CH0089_ExtraPassive: "Drill",
      Special_Pray: "Invocations",
      Special_CH0224_Public: "Passion",
      Special_CH0225_ExtraPassive: "Furin Kazan",
      Special_CH0233_ExtraPassive: "Sweet Potatoes",
      Special_CH0231_ExtraPassive: "Successful Protection",
      Special_CH0239_ExtraPassive: "Infiltration",
      Special_EN0008_Obelisk: "Overcharged",
      Special_CH0220_Public: "Sugar Rush",
      Special_CH0258_Public: "Bulletproof Plate",
      Special_CH0263_ExtraPassive_02: "Second Wind",
      Special_CH0271_Ex: "Leaflets",
      Special_AmplifyDoTAdditionalTick_Poison: "Poison Add. DMG",
      Special_AmplifyDoTReducePeriod_Chill: "Chill Interval Down",
      Special_CH0273_ExtraPassive: "Fan Service",
      Special_CH0275_Public: "Penlights",
      Special_EN0009_UnstableFlame: "Unstable Flame",
      Special_ExSkillCardRedrawStackDummy: "EX Redraw",
      Special_CH0280_Ex_01: "Duelling",
      Special_CH0280_Ex_02: "Ambition",
      Special_CH0245_Public: "Out",
    },
  },
} as const;

export type LocaleIdentifier = keyof typeof localizeTable;

type DotNotation<T extends object> = {
  [K in keyof T]: T[K] extends object
    ? `${Extract<K, string>}.${DotNotation<T[K]>}`
    : Extract<K, string>;
}[keyof T];

export type LocalizeKey = DotNotation<(typeof localizeTable)[LocaleIdentifier]>;

export function t(
  localizeKey: LocalizeKey,
  locale: LocaleIdentifier = "EN",
): string {
  const keys = localizeKey.split(".") as string[];
  let value: any = localizeTable[locale];

  const defaultValue = `No LocalizeKey ${localizeKey}`;

  try {
    for (const key of keys) {
      value = value[key];

      if (!value) {
        return defaultValue;
      }
    }
  } catch (err) {
    return defaultValue;
  }

  return value;
}
