export const DEFAULT_THREE_STAR_RATE = 0.03;
export const DEFAULT_PICKUP_RATE = 0;
export const DEFAULT_EXTRA_RATE = 0;

export const DEFAULT_BASE_ONE_STAR_RATE = 0.785;
export const DEFAULT_BASE_TWO_STAR_RATE = 0.185;
export const DEFAULT_BASE_THREE_STAR_RATE = 0.03;
